# Generated by Django 3.2.5 on 2021-07-04 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='docType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Notes_Type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='gradeName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Grade_Name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='subName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject_Name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapterName', models.CharField(max_length=255)),
                ('NotesType', models.CharField(max_length=255)),
                ('Notesfile', models.FileField(upload_to='Notes/')),
                ('GradeName', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Notes.gradename')),
                ('Subject', models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Notes.subname')),
            ],
        ),
    ]
